openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /purchaseItems:
    get:
      summary: List all purchaseItems
      operationId: listPurchaseItems
      tags:
        - purchaseItems
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of purchaseItems
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/PurchaseItems'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a purchaseItem
      operationId: createPurchaseItems
      tags:
        - purchaseItems
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchaseItems/{purchaseItemId}:
    get:
      summary: Info for a specific purchaseItem
      operationId: showPurchaseItemById
      tags:
        - purchaseItems
      parameters:
        - name: purchaseItemId
          in: path
          required: true
          description: The id of the purchaseItem to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/PurchaseItems'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /clients:
    get:
      summary: List all clients
      operationId: listClients
      tags:
        - clients
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of clients
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Clients'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a client
      operationId: createClients
      tags:
        - clients
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /clients/{clientId}:
    get:
      summary: Info for a specific client
      operationId: showClientById
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: The id of the client to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Clients'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - products
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of products
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Products'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a product
      operationId: createProducts
      tags:
        - products
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /products/{productId}:
    get:
      summary: Info for a specific product
      operationId: showProductById
      tags:
        - products
      parameters:
        - name: productId
          in: path
          required: true
          description: The id of the product to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Products'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchases:
    get:
      summary: List all purchases
      operationId: listPurchases
      tags:
        - purchases
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of purchases
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Purchases'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a purchase
      operationId: createPurchases
      tags:
        - purchases
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchases/{purchaseId}:
    get:
      summary: Info for a specific purchase
      operationId: showPurchaseById
      tags:
        - purchases
      parameters:
        - name: purchaseId
          in: path
          required: true
          description: The id of the purchase to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Purchases'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  


definitions:
  PurchaseItem:
    type: "object"
    required:
      - id
      - price
      - quantity
    properties:
      id:
        type: int
      price:
        type: number
      quantity:
        type: number
  PurchaseItems:
    type: array
    items:
      $ref: '#/definitions/PurchaseItem'
  Client:
    type: "object"
    required:
      - id
      - fullName
      - credentialsNonExpired
      - enabled
      - accountNonExpired
      - accountNonLocked
      - passwordChanged
      - username
      - password
      - avatar
      - fullName
      - about
    properties:
      id:
        type: int
      fullName:
        type: string
      credentialsNonExpired:
        type: boolean
      enabled:
        type: boolean
      accountNonExpired:
        type: boolean
      accountNonLocked:
        type: boolean
      passwordChanged:
        type: boolean
      username:
        type: string
      password:
        type: string
      avatar:
        type: string
      fullName:
        type: string
      about:
        type: string
  Clients:
    type: array
    items:
      $ref: '#/definitions/Client'
  Product:
    type: "object"
    required:
      - id
      - code
      - reference
    properties:
      id:
        type: int
      code:
        type: string
      reference:
        type: string
  Products:
    type: array
    items:
      $ref: '#/definitions/Product'
  Purchase:
    type: "object"
    required:
      - id
      - reference
      - purchaseDate
      - image
      - total
      - description
    properties:
      id:
        type: int
      reference:
        type: string
      purchaseDate:
        type: date
      image:
        type: string
      total:
        type: number
      description:
        type: string
  Purchases:
    type: array
    items:
      $ref: '#/definitions/Purchase'

  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
